### PR TITLE
solc 0.5.11

### PR DESCRIPTION
**Pull request by livnev**
needs `doCheck = false;` because of https://github.com/ethereum/solidity/issues/7297

cc @asymmetric

### CODE REVIEW

**Comment by asymmetric** [comment]
Why not actually open this upstream?

**Comment by livnev** [comment]
> Why not actually open this upstream?

`doCheck = false;` seems sloppy, I thought it would be better to wait and see if this can be resolved. Looks like the test should not have been expected. @asymmetric do you think I should apply [this patch](https://github.com/ethereum/solidity/pull/7298/files) and PR to upstream?

**Comment by livnev** [comment]
or better to just `doCheck = false;` and set it back in the next version?

**Comment by livnev** [comment]
Actually @asymmetric  have you ever tried building `solc` with CVC4 support? It seems that going forward the `SMTChecker` stuff is using CVC4 more and more.

**Pull request merged**
